language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "mngola-github"
    token:
      secure: "aeb56f79efb06ec91f8a749c3e39abaf76e82f9a"

jdk:
  - oraclejdk8
script:
  - curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux64-v0.15.0.tar.xz" | sudo tar -C /opt -xJ
  - ln -s "/opt/infer-linux64-v$VERSION/bin/infer" /usr/local/bin/infer
  - infer run -- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'